### ISSUE TITLE
Invalid VAT ID

### ISSUE THREAD

**Issue by vasco153** [ptisp/whmcs_module#11]
Oi, podem me ajudar, a versão é v7.10. Sou revendedor da ptisp. Não percebo o que fazer na parte do vat.
Obrigado

**Comment by joaograca** [comment]
Caro @vasco153 ,
Queira contactar a nossa equipa de suporte para que possamos dar o devido acompanhamento ao seu problema.
Poderá fazê-lo através da área de cliente (MyPTisp), através da criação de um novo ticket.
Estamos ao seu dispor.
